### ISSUE TITLE
Do we need to have Android Permission 

### ISSUE THREAD

**Issue by StanSarr** [AzizAK/react-native-detector#27]
Hi, 
Nice lib, 
Quick question: 
Do we need to ask for permission if we don't need to get the path of the screenshot? 
If we just wanna know if a screenshot is done by the user or not? 
Since we don't get the path on the react-native side
Thanks, 
Regards

**Comment by AzizAK** [comment]
unfortunately yes we need android permission, because android does not have an event or api to determine if the user took screenshot we have to look into the screenshots folder and check if there is new screenshot is saved that is why we need android permission. Check Snapchat for example is does't allow you to use the app until you accept the permissions.
